/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.edu.intecap.clinicaveterinaria.vista.paneles;

import co.edu.intecap.clinicaveterinaria.control.TipoMascotaDelegado;
import co.edu.intecap.clinicaveterinaria.modelo.vo.TipoMascotaVo;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author capacitaciones
 */
public class TipoMascotaPanel extends javax.swing.JPanel {
    private DefaultTableModel modelo;
    private final TipoMascotaVo tipoMascotaVo; 
    
    
    /**
     * Creates new form TipoMascotaPanel
     */
    public TipoMascotaPanel() {
        initComponents();
        configurarTabla();
        llenarTabla(new TipoMascotaDelegado(this).consultarTipoMascotas(),modelo);
        this.tipoMascotaVo = new TipoMascotaVo();
    }

    /**
     * metodo para obtener valores del GUI 
     */
    
    private void registrarTipoMascota() {
        tipoMascotaVo.setNombre(txtNombre.getText());
        tipoMascotaVo.setEstado(cbxEstado.isSelected());
        // validar si el id de la constante es mayor a cero  
        if (tipoMascotaVo.getIdTipoMascota() < 1) {
           // se crea un nuevo registro de tipo mascota
           new TipoMascotaDelegado(this).insertarTipoMascota(tipoMascotaVo);
        } else {
            new TipoMascotaDelegado(this).editarTipoMascota(tipoMascotaVo);
        }
        
        // mensaje de confirmacion de registro
        JOptionPane.showMessageDialog(this, 
                    "Tipo de mascota registrado",
                    "Registro de Datos",
                    JOptionPane.INFORMATION_MESSAGE);
        refrescarTabla();
        limpiarCampos();
        limpiarConstante();
        
    }
    
    /** 
     * Carga los parametros de la tabla 
     */
    
    private void configurarTabla(){
        modelo = new DefaultTableModel();
        modelo.addColumn("Id Mascota");
        modelo.addColumn("Nombre");
        modelo.addColumn("Estado");
        tblTipoMascota.setModel(modelo);
        tblTipoMascota.getSelectionModel().addListSelectionListener(tableListener);
        
    }
    
    /**
     * Carga una lista de tipo de mascotas desde la base de datos a la tabla de la interfaz grafica de usuario
     * @param ListaTipoMascota  Lista de tipo de mascotas de la base de datos
     * @param modelo  Modelo de tabla con la estructuta de los datos a cargar
     */
    private void llenarTabla(List<TipoMascotaVo> ListaTipoMascota, DefaultTableModel modelo){
        for (TipoMascotaVo tipoMascotaVo : ListaTipoMascota) {
            Object [] fila = new Object[3];
            fila[0] = tipoMascotaVo.getIdTipoMascota();
            fila[1] = tipoMascotaVo.getNombre();
            fila[2] = tipoMascotaVo.isEstado();
            modelo.addRow(fila);
        }
        tblTipoMascota.updateUI();
        
    }
    
    
    /**
     * Actualiza la informacion de la tabla con cada vez que se realiza un registro 
     */
    private void refrescarTabla() {
        modelo.setRowCount(0);
        List<TipoMascotaVo> listaMascotas = new TipoMascotaDelegado(this).consultarTipoMascotas();
        llenarTabla(listaMascotas, modelo);        
    }
    
    private void limpiarCampos(){
        txtNombre.setText("");
        cbxEstado.setSelected(false);
    }

    
    /**
     * Reinicia los valores de la contante que se usa para insertar o actualizar un registor de la tabla tipo_mascota
     */
    private void limpiarConstante() {
        // Limpiar el id de tipo de mascota
        tipoMascotaVo.setIdTipoMascota(0);
        // limpiar el nombre del tipo mascota
        tipoMascotaVo.setNombre("");
        // limpiar el estado del tipo mascota
        tipoMascotaVo.setEstado(false);
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTipoMascota = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();

        jLabel1.setText("Nombre:");

        txtNombre.setText("jTextField1");

        jLabel2.setText("Estado:");

        cbxEstado.setText("Activo");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        tblTipoMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTipoMascota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxEstado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 135, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(cbxEstado))
                    .addComponent(btnGuardar))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.registrarTipoMascota();
    }//GEN-LAST:event_btnGuardarActionPerformed
    
    /**
     * Permite obtener el id de un registro de la tbla con datos de la base de datos con el fin de realizar 
     * el trabajo de edicion de un registro, para ello se usa un objeto que represente 
     * un registro de la tabla de la base de datos (Vo), para luego enviar dichos datos como parte de los parametros 
     * de la actualizacion
     */
    
    ListSelectionListener tableListener = new ListSelectionListener() {
        @Override
        public void valueChanged(ListSelectionEvent e) {
            // validar si se ha seleccionado una fila de la tabla
           if (tblTipoMascota.getSelectedRow() > -1) {
               // Se obtiene el id de la fila seleccionada en la tabla
               // int id --> variable que guarda el id_tipo_mascota de la fila seleccionada
               // (int) --> casteo del objeto que se  obtiene al seleccionar una fila de la tabla de la interfaz grafica de usuario
               // se castea a un dato de tipo int 
               // tblTipoMascota.getValueAt --> Metodo que permite obtener el dato de una celda de la tabla segun dos parametros
               // "(fila, columna)" este metodo retorna un objeto de tipo object
               // getSelectedRow() --> metodo que retorna el numero de la fila sobre la cual se ha realizado una seleccion con el mouse
               // 0 -->  representa el indice de la columna seleccionada, siempre es cero porque representa la primera columna de la tabla
               int id = (int) tblTipoMascota.getValueAt(tblTipoMascota.getSelectedRow(),0);
               // consultar en la base de datos por ese id seleccionado y 
               // guardar el resultado de la consulta en un nuevo objeto de TipoMascotaVo
               TipoMascotaVo tMvo = new TipoMascotaDelegado(TipoMascotaPanel.this).consultarTipoMascota(id);
               //asignar los valores obtenidos de la consulta  a la constante
               tipoMascotaVo.setIdTipoMascota(tMvo.getIdTipoMascota());
               tipoMascotaVo.setNombre(tMvo.getNombre());
               tipoMascotaVo.setEstado(tMvo.isEstado());
               //llenar campos del formulario
               llenarCampos();
           }
        }
    };

    private void llenarCampos() {
        txtNombre.setText(tipoMascotaVo.getNombre());
        cbxEstado.setSelected(tipoMascotaVo.isEstado());
    }
            
            
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JCheckBox cbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblTipoMascota;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}



